### ISSUE TITLE
Game does not restart.

### ISSUE THREAD

**Issue by blui22** [ImagicalGamer/SurvivalGamesV3#44] opened 2016-03-19 15:11 UTC
I am running the latest version of IM and the game will not end. It just keeps repeating Game ending in 1 seconds....

**Comment by remotevase** [comment] 2016-03-19 15:14
Can anybody else confirm this?

**Comment by ImagicalGamer** [comment] 2016-03-19 18:37
Not a confirmed bug re-make your arena.

**Comment by ImagicalGamer** [comment] 2016-03-19 19:25
That was caused by our time mix up with the grace period, xD it added 300 ticks to the game when there was 1 second left making the game infinite, issue fixed now.

**Closed by ImagicalGamer** 2016-03-19 19:25 UTC
Labels: help wanted, question

**Comment by remotevase** [comment] 2016-03-19 20:31
XD that issue was hilarious
