### ISSUE TITLE
PocketMine/ImagicalMine Bug Report!

### ISSUE THREAD

**Issue by kaitododoyt** [ImagicalGamer/SurvivalGamesV3#20] opened 2016-03-13 00:26 UTC
the plugin have god mode?

**Comment by ImagicalGamer** [comment] 2016-03-13 00:27
If you mean a "grace period" no. If you have spawn protection and peaceful spawn it will make parts of the map "safe zones". Grace period coming in a later version.

**Comment by kaitododoyt** [comment] 2016-03-13 00:38
ok thanks, good work only need invencibility period and solve the bug when player dies

**Comment by ImagicalGamer** [comment] 2016-03-13 00:45
Explain the bug please? Is it the one where the player stays in the arena?

**Comment by kaitododoyt** [comment] 2016-03-13 01:26
yes, the winner stay in arena until the loser press reappear

**Comment by ImagicalGamer** [comment] 2016-03-13 01:28
Ah, so when the loser "respawns" the winner is teleported to the Default Level?

**Comment by ImagicalGamer** [comment] 2016-03-13 02:33
I just updated it so when the player respawns they go to the Hub world. There's not much that can be done about your issue. The player stays in the world they died in until they respawn.

**Comment by remotevase** [comment] 2016-03-13 13:14
I will try to add grace period today, but it may not work out, so I will make "main2.php" and edit in there (so that the plugin is not majorly corrupted, lol)

**Comment by MacHupTR** [comment] 2016-03-13 13:36
@ImagicalGamer 
![screenshot_2016-03-13-15-34-38-1](https://cloud.githubusercontent.com/assets/16403705/13728972/62f42b94-e931-11e5-992c-f44dd4f6458d.png)

Help me

**Comment by remotevase** [comment] 2016-03-13 13:52
> @ImagicalGamer 
screenshot_2016-03-13-15-34-38-1

Help me <

What are you using? Pocketmine? ImagicalMine? Genysis?

**Comment by MacHupTR** [comment] 2016-03-13 14:35
@remotevase pocketmine

**Comment by ImagicalGamer** [comment] 2016-03-13 14:37
@MacHupTR You can download from this repo now the issue is fixed.

**Comment by MacHupTR** [comment] 2016-03-13 14:39
@ImagicalGamer  THX :+1:

**Comment by ImagicalGamer** [comment] 2016-03-13 14:40
Use this: https://github.com/ImagicalGamer/SurvivalGamesV3/releases/tag/V3.0.2

**Comment by ImagicalGamer** [comment] 2016-03-13 14:41
We have a test file on the repo that will cause the plugin to crash so only use the releases I issue.

**Comment by ImagicalGamer** [comment] 2016-03-13 20:49
New bug report issue thread thing. xP

**Comment by kaitododoyt** [comment] 2016-03-13 21:58
Can you change the [X Y Z] Spawns positions with -1 in Y coord. for better movement?. I change this in my config.yml and works better

**Comment by kaitododoyt** [comment] 2016-03-13 22:02
last build error:

syntax error, unexpected 'else' (T_ELSE) in phar://C:/Users/Kaito/Desktop/K                                                                                aito's Server/plugins/phar_SurvivalGamesV3-master_61fB9HViyYWgWAE.phar/src/SurvivalGames                                                                                V3/SurvivalGamesV3.php on line 149
[19:01:10] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server                                                                                 has crashed. Creating a crash dump

**Comment by ImagicalGamer** [comment] 2016-03-13 22:16
I will add that, the error you put was because it was a test build, there was a syntax error it is fixed now. It is only recommended  to run the latest release [HERE](https://github.com/ImagicalGamer/SurvivalGamesV3/releases/tag/V3.0.2). It says there are 32 new commits but I keep it updated with the latest stable version.

**Comment by ImagicalGamer** [comment] 2016-03-13 22:18
0,0,-1 <- that what you meant? @kaitododoyt

**Comment by ImagicalGamer** [comment] 2016-03-13 22:19
Instead of 0,0 where it teleports 0,0,-1. That could fix the player jumping problem.

**Comment by kaitododoyt** [comment] 2016-03-15 02:54
last version:

[Server thread/CRITICAL]: ReflectionException: "Class SurvivalGamesV3\PlayerJoinEvent does not exist" (EXCEPTION) in "/src/pocketmine/plugin/PluginManager" at line 704

**Comment by remotevase** [comment] 2016-03-15 14:40
Oopsies, small issue... Thats an easy fix, fixing it now

**Comment by remotevase** [comment] 2016-03-15 14:43
Hmm... line 704 doesn't even exist... @ImagicalGamer what's the problem here?

**Comment by ImagicalGamer** [comment] 2016-03-15 16:53
@remotevase it's the file you added, it causes that error. Please don't compile the plugin from the repo only USE the releases I publish on ImagicalMine forums.

**Comment by ImagicalGamer** [comment] 2016-03-15 16:57
An update will be released today.

**Comment by ImagicalGamer** [comment] 2016-03-16 00:40
Download latest update [HERE](forums.imagicalmine.net/plugins/survivalgames.68/download?version=129)! Bug fixes and **_FULL_** ranks have been implemented! @remotevase you said you were working on a grace period, is that in TestMain?

**Comment by remotevase** [comment] 2016-03-16 14:28
Yup, in TestMain. Haven't committed changes yet, working on it on my own time

**Comment by ImagicalGamer** [comment] 2016-03-16 14:30
Sounds good. xD

**Comment by astersx** [comment] 2016-03-16 16:29
Hi,  you can add grace period,  like how simpleAuth  do.  Uregistered players cant be killed!!!

**Comment by erkam2002** [comment] 2016-03-16 18:17
Genisys Crash Dump Wed Mar 16 18:14:33 UTC 2016

Error: Can't use method return value in write context
File: /SG.phar/src/SurvivalGamesV3/SurvivalGamesV3
Line: 69
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起

Code:
[60] 	}
[61] 	
[62] 	Public function playerDeath($spawn) {
[63]         $spawn = $this->getServer()->getDefaultLevel()->getSafeSpawn(); 
[64]         $this->getServer()->getDefaultLevel()->loadChunk($spawn->getFloorX(), 
[65]         $spawn->getFloorZ()); $player->teleport($spawn,0,0);
[66] 	}
[67]         public function playerLogin(PlayerLoginEvent $spawn){
[68]         $spawn = $this->getServer()->getDefaultLevel()->getSafeSpawn(); 
[69]         $this->getServer() = getDefaultLevel()->loadChunk($spawn->getFloorX(), 
[70]         $spawn->getFloorZ()); $spawn->teleport($spawn,0,0);
[71] 		}
[72]         
[73] 	public function onMove(PlayerMoveEvent $event)
[74] 	{
[75] 		$player = $event->getPlayer();
[76] 		$level = $player->getLevel()->getFolderName();
[77] 		if(in_array($level,$this->arenas))
[78] 		{
[79] 			$config = new Config($this->getDataFolder() . "/config.yml", Config::YAML);

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.1dev #154 [Protocol 45; API 2.0.0]
uname -a: Linux mc12 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
加载的插件:
BanItem 2.2 by LDX for API(s) 1.0.0, 2.0.0
SWorldEditor Beta_1.5 by Sergey_Dertan for API(s) 1.8.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
xyz 1.0.1 by unerds for API(s) 1.0.0
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
LaunchPads 1.0.0 by MCPEPIG for API(s) 1.0.0
ManyWorlds 2.0.3 by aliuly for API(s) 2.0.0, 1.13.0
PurePerms 1.3.6 by 64FF00 for API(s) 1.13.0, 2.0.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0
AntiCheat 1.1-R2 by DarkWav (Darku) for API(s) 1.14.0, 2.0.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0

Crash

**Comment by ImagicalGamer** [comment] 2016-03-16 18:20
It clearly said don't download. Error being fixed.

**Comment by remotevase** [comment] 2016-03-16 18:25
Goodness, @astersx I have said, multiple times, might I add, that I am working on the grace period.

**Comment by ImagicalGamer** [comment] 2016-03-16 18:27
@erkam2002 This plugin was made for ImagicalMine, there are Genisys errors that I cannot fix without causing ImagicalMine errors. (I tried)

**Comment by remotevase** [comment] 2016-03-16 18:29
@ImagicalGamer should we make a seperate branch for genysis?

**Comment by ImagicalGamer** [comment] 2016-03-16 18:30
@remotevase Probs. I'll test a Genisys version of it now to see what bugs there are and fix some.

**Comment by ImagicalGamer** [comment] 2016-03-16 19:02
Genisys updated! ImagicalMine version also updated! Prevents the possibility of IM players seeing that issue.

**Comment by remotevase** [comment] 2016-03-16 19:05
lol yay! not many issues being reported...

**Comment by erkam2002** [comment] 2016-03-20 14:59
https://www.dropbox.com/s/i06un9dtnecs9gr/MP_SWorldEditor.phar?dl=0

**Comment by ImagicalGamer** [comment] 2016-03-20 14:59
Thx.

**Comment by remotevase** [comment] 2016-03-20 15:04
cool, thanks. IDK why that was brought up in here, but I like it!

**Comment by kaitododoyt** [comment] 2016-03-20 16:09
Players in same spawn:

this occurs when players join(2 or more), then a first player leaves the game and when reenters appears in the same place where there is already someone.

**Comment by remotevase** [comment] 2016-03-20 16:22
oh, yes. that makes sense. I don't think there is a way to fix that...

**Comment by ImagicalGamer** [comment] 2016-03-20 16:22
Ah, that makes sense SG saves some player data.

**Comment by remotevase** [comment] 2016-03-20 16:22
well, we won't change the player data XD

**Comment by ImagicalGamer** [comment] 2016-03-20 16:26
after we get grace period we could possibly fix this. When the player hits the sign we would have to get the XYZ of the plate and check if any players are there.

**Comment by remotevase** [comment] 2016-03-20 16:29
oh. so tough... well, thats why there are two of us! (actually 3, if you include @austina1212)

**Comment by ImagicalGamer** [comment] 2016-03-20 16:31
Yep!

**Comment by ImagicalGamer** [comment] 2016-03-20 16:32
Debating if I publish my SkyWars plug or not, (remake of dis with world restore).

**Comment by remotevase** [comment] 2016-03-20 16:34
you should. Same basis for this code can be used for many, many things

**Closed** 2016-03-27 14:40 UTC
Labels: bug, enhancement, help wanted, question
